# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# Theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"

minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en_US"
title                    : "Glenn Lanzer III"
title_separator          : "-"
name                     : "Glenn Lanzer III"
description              : &description "Glenn's personal website"
logo                     : "/assets/images/android-chrom-384x384.png"
teaser                   : "/assets/images/default-teaser.png" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
url                      : "https://TexasBullet26.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "TexasBullet26/TexasBullet26.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
breadcrumbs              : true # true, false (default)
words_per_minute         : 200

comments:
  provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch                 : "master"

# reCAPTCHA keys
reCaptcha:
  siteKey                : "6LeOsEoUAAAAAHzxxTROVvAnwL1ZyGmox8kPvxI5"
  secret                 : "q0dgxcNln6DrFdDziU2JEgF3DAZJXAqtQ/XumFFKhxdacuvnXQGEgOnDZyIBk1xF+zKKUA+Bw6thoz4hCnp8yN45k8o2vtjPbQwMWrI2wIAeNDb7GMjD01mTEssE7eY5cG3C5+hlCXLUnflePf1Mgy9FPl+esKYF56thZlpOVew="

atom_feed:
  path                   : "https://TexasBullet26.github.io/atom.xml" # blank (default) uses feed.xml

search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false

# SEO Related
# google_site_verification :
# bing_site_verification   :
# yandex_site_verification :
# naver_site_verification  :

# Social Sharing
twitter:
  username               : &twitter "LanzerTrey26"
facebook:
  username               : &facebook "trey.lanzer"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/site-logo.png" # Open Graph/Twitter default site image

# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles

social:
  type                   : # Person or Organization (defaults to Person)
  name                   : "Glenn Lanzer III" # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/LanzerTrey26"
    - "https://www.facebook.com/trey.lanzer"
    - "https://www.instagram.com/treylanzer/"
    - "https://github.com/TexasBullet26"
    - "https://plus.google.com/u/0/+lanzertrey/posts"

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-99924733-3"


# Site Author
author:
  name             : "Glenn Lanzer III"
  uri              : "https://TexasBullet26.github.io/about/"
  url              : "https://TexasBullet26.github.io/about/"
  avatar           : "/assets/images/bio-pic.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am a fullstack web developer located near Dallas, TX. I am currently available for hire and looking for clients. If you like what you see and are interested in me building your website, or anything related, to your customizations, fell free to [contact me](https://TexasBullet26.github.io/contact/)"
  location         : "Denton, TX"
  email            : "lanzertrey@gmail.com"
  uri              : "https://TexasBullet26.github.io"
  home             : "https://TexasBullet26.github.io" # null (default), "absolute or relative url to link to author home"
  codepen          : "TexasBullets26"
  facebook         : "trey.lanzer"
  github           : "TexasBullet26"
  google_plus      : "lanzertrey"
  instagram        : "treylanzer"
  linkedin         : "glenn-lanzer" # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  # soundcloud       : "texasbullet26"
  # stackoverflow    : "7509354/texasbullet-26" # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  # tumblr           : "texasbullet26"
  twitter          : "LanzerTrey26"
  # youtube          : # "https://youtube.com/c/MichaelRoseDesign"

twitter:
  username         : "LanzerTrey26"

# JEKYLL CONFIGURATION
# Conversion
permalink: /:categories/:title/
future: false
show_drafts: false
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
# Reading Files
keep_files:
  - .git
  - .svn
include:
  - .htaccess
  - ["_pages"]
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Chicago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

#  Plugins (previously gems:)
plugins:
  # - jekyll
  - commonmarker
  - jekyll-sass-converter
  - html-pipeline
  - jekyll-avatar
  # - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-tagging-related_posts
  - jekyll-algolia
  - jekyll-paginate-v2
  - jekyll-typogrify
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-data
  - jemoji
  - kramdown
  - liquid

# mimic GitHub Pages with --safe
whitelist:
  # - jekyll
  - commonmarker
  - jekyll-sass-converter
  - html-pipeline
  - jekyll-avatar
  # - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-tagging-related_posts
  - jekyll-algolia
  - jekyll-paginate-v2
  - jekyll-typogrify
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-data
  - jemoji
  - kramdown
  - liquid

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled: true
    []
    - categories
    - tags
  layouts:
    category: "archive-taxonomy"
    tag: "archive-taxonomy"
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    category: "/categories/:name/"
    tag: "/tags/:name/"

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  portfolio:
    output: true
    permalink: "/:collection/:path/"
    title: "Portfolio"

# Front Matter Defaults
defaults:
  # _posts / Blog Articles in _posts subdirectory
  - scope:
      path: ""
      type: posts
    values:
      layout: single # posts will use the single layout
      category: posts
      author_profile: true
      read_time: true # enable reading time
      support: true
      comments: # true # enable comments
      share: true # enable social sharing links 
      related: true # enable related posts
      image:
        cover: true
      breadcrumbs:
        - label: "Blog Articles"
          url: /posts/
  # TIL (Today I Learned)
  - scope:
      path: "" # _posts/til
      type: posts
    values:
      layout: post
      category: til
      read_time: true
      comments: true
      support: true
      share: true
      related: true
      breadcrumbs:
        - label: "Today I Learned"
          url: /til/
  # Projects
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
      category: portfolio
      breadcrumbs:
        - label: "Portfolio"
          url: /portfolio/
  # Pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  debug: false
  per_page: 15
  permalink: "/page/:num/"
  title: ":title - Page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    slugify:
      mode: raw
      cased: true
    layouts:
      - "single.html"
    title: ":tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"

# Plugin: Jekyll Algolia
# algolia:
 # application_id: #
  # index_name: #
  # search_only_api_key: #
  # nodes_to_index: "p"
  # files_to_exclude:
    # - index.html
    # - index.md
    # - excluded-file.html
    # - _pages/404.md
    # - _pages/articles.md
    # - _pages/faqs.md
    # - _pages/sitemap.md
    # - _pages/tag.md
    # - _pages/til.md
    # - _pages/work.md
